// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





import "./globals.css";
// import ReduxProvider from "../providers/ReduxProvider.tsx";
import ReduxProvider from "@/providers/ReduxProvider";
export const metadata = {
  title: "CafeEase",
  description: "description",
  openGraph: {
    title: "CafeEase",
    description: "sdescription",
    images: [
      {
        url: "/icon.png", // inside /public
        width: 1200,
        height: 630,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
  dangerouslySetInnerHTML={{
    __html: `
     <script
  defer
  src="https://analytica.gaurabkhanal.com.np/analytica.js"
  data-analytica-api="https://fyp-uoth.onrender.com"
  data-analytica-key="anl_d04a395a34996303c5946282712977e89420da77ba2cf5d5320b6a7e88c7db16"
></script>
    `,
  }}
/>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
