const BaseModel = require('./BaseModel');
const db = require('../config/database');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

class Staff extends BaseModel {
  constructor() {
    super('staff');
  }

  async findByEmailAndHotel(email, hotelId) {
    const query = 'SELECT * FROM staff WHERE email = $1 AND hotel_id = $2';
    const result = await db.query(query, [email, hotelId]);
    return result.rows[0];
  }

  async findByStaffCode(staffCode, hotelId) {
    const query = 'SELECT * FROM staff WHERE staff_code = $1 AND hotel_id = $2';
    const result = await db.query(query, [staffCode, hotelId]);
    return result.rows[0];
  }

  async createStaff(hotelId, staffData, createdBy) {
    // Validate email format
    const emailRegex = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
    if (!emailRegex.test(staffData.email)) {
      throw new Error('Invalid email format');
    }

    // Check if email already exists in this hotel
    const existing = await this.findByEmailAndHotel(staffData.email, hotelId);
    if (existing) {
      throw new Error('Email already exists for this hotel');
    }

    // Hash password
    const salt = await bcrypt.genSalt(10);
    staffData.password_hash = await bcrypt.hash(staffData.password, salt);
    delete staffData.password;

    // Set hotel and creator
    staffData.hotel_id = hotelId;
    staffData.created_by = createdBy;
    staffData.permissions = JSON.stringify(staffData.permissions || {});

    // Staff code will be generated by database trigger
    const staff = await this.create(staffData);

    return staff;
  }

  async verifyPassword(password, hashedPassword) {
    return await bcrypt.compare(password, hashedPassword);
  }

  async updateLastLogin(staffId) {
    return await this.update(staffId, { last_login: new Date() });
  }

  async getStaffByHotel(hotelId, filters = {}) {
    let query = 'SELECT * FROM staff WHERE hotel_id = $1';
    const values = [hotelId];
    let paramCount = 2;

    if (filters.role) {
      query += ` AND role = $${paramCount}`;
      values.push(filters.role);
      paramCount++;
    }

    if (filters.is_active !== undefined) {
      query += ` AND is_active = $${paramCount}`;
      values.push(filters.is_active);
      paramCount++;
    }

    query += ' ORDER BY created_at DESC';

    const result = await db.query(query, values);
    return result.rows;
  }

  async getStaffLoginInfo(staffId) {
    const query = `
      SELECT 
        s.*,
        sl.login_username,
        h.hotel_slug,
        h.hotel_name
      FROM staff s
      JOIN staff_login sl ON s.id = sl.staff_id
      JOIN hotels h ON s.hotel_id = h.id
      WHERE s.id = $1 AND s.is_active = true AND s.can_login = true AND sl.is_active = true
    `;
    
    const result = await db.query(query, [staffId]);
    return result.rows[0];
  }

  async disableLogin(staffId) {
    await db.query(
      'UPDATE staff_login SET is_active = false WHERE staff_id = $1',
      [staffId]
    );
    return await this.update(staffId, { can_login: false });
  }

  async enableLogin(staffId) {
    await db.query(
      'UPDATE staff_login SET is_active = true WHERE staff_id = $1',
      [staffId]
    );
    return await this.update(staffId, { can_login: true });
  }
}

module.exports = new Staff();