// app/register/page.tsx
"use client";

import {
  useState,
  useEffect,
  Suspense,
  useMemo,
  useRef,
  useCallback,
} from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  Hotel,
  ArrowLeft,
  ArrowRight,
  Check,
  Loader2,
  Building2,
  User,
  MapPin,
  Briefcase,
  CreditCard as CardIcon,
  FileText,
  FileCheck,
  Edit,
  CheckCircle,
  Users,
  Table,
  Utensils,
  Percent as PercentIcon,
  Eye,
  EyeOff,
  Shield,
  AlertCircle,
  Gift,
  Clock,
  Zap,
  Wallet,
  Landmark,
  Smartphone,
} from "lucide-react";
import toast, { Toaster } from "react-hot-toast";
import { useDispatch, useSelector } from "react-redux";
import type { AppDispatch, RootState } from "@/store/index";
import { fetchSubscriptionPlans } from "@/store/slices/subscriptionSlice";
import { useTerms } from "@/hooks/useTerms";
import { acceptTerms } from "@/store/slices/termsSlice";
import { useHotelRegistration } from "@/hooks/useHotelRegistration";
import {
  hotelRegistrationService,
  type BillingCycle,
  type PaymentMethod,
  type RegistrationType,
  type SubscriptionPlan,
} from "@/services/hotelRegistration.service";

const ChevronUp = ({ className }: { className?: string }) => (
  <svg
    className={className}
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M5 15l7-7 7 7"
    />
  </svg>
);

const ChevronDown = ({ className }: { className?: string }) => (
  <svg
    className={className}
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M19 9l-7 7-7-7"
    />
  </svg>
);

const getActualErrorMessage = (error: any): string => {
  if (typeof error === "string") return error;

  const data = error?.response?.data || error?.data || error;

  if (Array.isArray(data?.errors) && data.errors.length > 0) {
    const firstError = data.errors[0];
    if (firstError?.message) return firstError.message;
    if (typeof firstError === "string") return firstError;
  }

  if (data?.message && data.message !== "Validation failed") {
    return data.message;
  }

  if (Array.isArray(error?.errors) && error.errors.length > 0) {
    const firstError = error.errors[0];
    if (firstError?.message) return firstError.message;
  }

  return data?.message || error?.message || "Something went wrong";
};

// ===================== STEP 1 =====================
function HotelDetailsStep({
  formData,
  updateFormData,
  errors,
  setFieldError,
  clearFieldError,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  setFieldError: (field: string, error: string) => void;
  clearFieldError: (field: string) => void;
}) {
  const [slugPreview, setSlugPreview] = useState("");
  const [imageError, setImageError] = useState("");
  const hasAutoGeneratedRef = useRef(false);
  const prevHotelNameRef = useRef(formData.hotel_name);

  useEffect(() => {
    if (!formData.hotel_name.trim()) {
      setFieldError("hotel_name", "Hotel name is required");
    } else {
      clearFieldError("hotel_name");
    }
  }, [formData.hotel_name, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.hotel_slug.trim()) {
      setFieldError("hotel_slug", "URL slug is required");
    } else {
      clearFieldError("hotel_slug");
    }
  }, [formData.hotel_slug, setFieldError, clearFieldError]);

  useEffect(() => {
    if (prevHotelNameRef.current !== formData.hotel_name) {
      prevHotelNameRef.current = formData.hotel_name;

      const slug = formData.hotel_name
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/--+/g, "-")
        .trim();

      setSlugPreview(slug);

      if (
        !formData.hotel_slug &&
        formData.hotel_name &&
        !hasAutoGeneratedRef.current
      ) {
        hasAutoGeneratedRef.current = true;
        updateFormData("hotel_slug", slug);
      }
    }
  }, [formData.hotel_name, formData.hotel_slug, updateFormData]);

  const imagePreview = useMemo(() => {
    if (!formData.image) return null;
    return URL.createObjectURL(formData.image);
  }, [formData.image]);

  useEffect(() => {
    return () => {
      if (imagePreview) URL.revokeObjectURL(imagePreview);
    };
  }, [imagePreview]);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null;

    if (!file) {
      updateFormData("image", null);
      setImageError("");
      clearFieldError("image");
      return;
    }

    if (!file.type.startsWith("image/")) {
      updateFormData("image", null);
      setImageError("Please select a valid image file.");
      setFieldError("image", "Please select a valid image file.");
      e.target.value = "";
      return;
    }

    const maxSizeInBytes = 2 * 1024 * 1024;
    if (file.size > maxSizeInBytes) {
      updateFormData("image", null);
      setImageError("Image size must be 2MB or less.");
      setFieldError("image", "Image size must be 2MB or less.");
      e.target.value = "";
      return;
    }

    updateFormData("image", file);
    setImageError("");
    clearFieldError("image");
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">
          Cafe/Resturant Information
        </h3>
        <p className="text-gray-600">Tell us about your Cafe or restaurant</p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Cafe/Restaurant Name *
          </label>
          <input
            type="text"
            value={formData.hotel_name}
            onChange={(e) => updateFormData("hotel_name", e.target.value)}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.hotel_name ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="Grand Hotel & Resort"
          />
          {errors.hotel_name && (
            <p className="mt-1 text-sm text-red-600">{errors.hotel_name}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
             URL Slug *
          </label>
          <div className="flex items-center gap-3">
            <span className="text-gray-500 whitespace-nowrap">
              CloudCafe.com/
            </span>
            <input
              type="text"
              value={formData.hotel_slug}
              onChange={(e) => {
                updateFormData("hotel_slug", e.target.value);
                hasAutoGeneratedRef.current = false;
              }}
              className={`flex-1 px-4 py-3 rounded-xl border ${
                errors.hotel_slug ? "border-red-300" : "border-gray-300"
              } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
              placeholder="grand-hotel-resort"
            />
          </div>
          {errors.hotel_slug && (
            <p className="mt-1 text-sm text-red-600">{errors.hotel_slug}</p>
          )}
          <p className="mt-1 text-sm text-gray-500">
            This will be your unique URL. Example: CloudCafe.com/
            {slugPreview || "your-hotel"}
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Hotel Image
          </label>

          <input
            type="file"
            accept="image/*"
            onChange={handleImageChange}
            className={`w-full px-4 py-3 rounded-xl border ${
              imageError || errors.image ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors file:mr-4 file:rounded-lg file:border-0 file:bg-amber-50 file:px-4 file:py-2 file:text-sm file:font-medium file:text-amber-700 hover:file:bg-amber-100`}
          />

          {imageError && (
            <p className="mt-1 text-sm text-red-600">{imageError}</p>
          )}

          {!imageError && errors.image && (
            <p className="mt-1 text-sm text-red-600">{errors.image}</p>
          )}

          <p className="mt-1 text-sm text-gray-500">
            Upload JPG, PNG, or WebP image up to 2MB.
          </p>

          {formData.image && imagePreview && (
            <div className="mt-4">
              <p className="text-sm font-medium text-gray-700 mb-2">Preview</p>
              <div className="w-40 h-40 rounded-xl border border-gray-200 overflow-hidden bg-gray-50">
                <img
                  src={imagePreview}
                  alt="Hotel preview"
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="mt-2 flex items-center justify-between text-sm text-gray-600">
                <span className="truncate max-w-[220px]">
                  {formData.image.name}
                </span>
                <button
                  type="button"
                  onClick={() => {
                    updateFormData("image", null);
                    setImageError("");
                    clearFieldError("image");
                  }}
                  className="text-red-600 hover:text-red-700 font-medium"
                >
                  Remove
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ===================== STEP 2 =====================
function AdminDetailsStep({
  formData,
  updateFormData,
  errors,
  setFieldError,
  clearFieldError,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  setFieldError: (field: string, error: string) => void;
  clearFieldError: (field: string) => void;
}) {
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [passwordStrength, setPasswordStrength] = useState("");

  useEffect(() => {
    if (!formData.admin_name.trim()) setFieldError("admin_name", "Admin name is required");
    else clearFieldError("admin_name");
  }, [formData.admin_name, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.admin_email.trim()) setFieldError("admin_email", "Email is required");
    else clearFieldError("admin_email");
  }, [formData.admin_email, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.admin_phone.trim()) setFieldError("admin_phone", "Phone number is required");
    else clearFieldError("admin_phone");
  }, [formData.admin_phone, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.admin_password) {
      setFieldError("admin_password", "Password is required");
      setPasswordStrength("");
      return;
    }

    clearFieldError("admin_password");

    const hasUpper = /[A-Z]/.test(formData.admin_password);
    const hasLower = /[a-z]/.test(formData.admin_password);
    const hasNumber = /\d/.test(formData.admin_password);
    const hasSpecial = /[^\w\s]/.test(formData.admin_password);
    const length = formData.admin_password.length;

    if (length >= 8 && hasUpper && hasLower && hasNumber && hasSpecial) {
      setPasswordStrength("Strong");
    } else if (
      length >= 8 &&
      ((hasUpper && hasLower) || (hasLower && hasNumber) || (hasUpper && hasNumber))
    ) {
      setPasswordStrength("Medium");
    } else if (length > 0) {
      setPasswordStrength("Weak");
    } else {
      setPasswordStrength("");
    }
  }, [formData.admin_password, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.admin_confirm_password) {
      if (formData.admin_password) {
        setFieldError("admin_confirm_password", "Please confirm your password");
      } else {
        clearFieldError("admin_confirm_password");
      }
      return;
    }

    if (formData.admin_password !== formData.admin_confirm_password) {
      setFieldError("admin_confirm_password", "Passwords do not match");
    } else {
      clearFieldError("admin_confirm_password");
    }
  }, [
    formData.admin_password,
    formData.admin_confirm_password,
    setFieldError,
    clearFieldError,
  ]);

  const getPasswordStrengthColor = () => {
    switch (passwordStrength) {
      case "Strong":
        return "text-green-600";
      case "Medium":
        return "text-yellow-600";
      case "Weak":
        return "text-orange-600";
      default:
        return "text-gray-500";
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">Admin Account</h3>
        <p className="text-gray-600">Create your administrator account</p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Full Name *
          </label>
          <input
            type="text"
            value={formData.admin_name}
            onChange={(e) => updateFormData("admin_name", e.target.value)}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.admin_name ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="John Smith"
          />
          {errors.admin_name && (
            <p className="mt-1 text-sm text-red-600">{errors.admin_name}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Email Address *
          </label>
          <input
            type="email"
            value={formData.admin_email}
            onChange={(e) => updateFormData("admin_email", e.target.value)}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.admin_email ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="admin@yourhotel.com"
          />
          {errors.admin_email && (
            <p className="mt-1 text-sm text-red-600">{errors.admin_email}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Phone Number *
          </label>
          <input
            type="tel"
            value={formData.admin_phone}
            onChange={(e) => updateFormData("admin_phone", e.target.value)}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.admin_phone ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="1234567890"
          />
          {errors.admin_phone && (
            <p className="mt-1 text-sm text-red-600">{errors.admin_phone}</p>
          )}
          <p className="mt-1 text-sm text-gray-500">
            Enter 10-digit phone number (numbers only)
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Password *
            </label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                value={formData.admin_password}
                onChange={(e) =>
                  updateFormData("admin_password", e.target.value)
                }
                className={`w-full px-4 py-3 rounded-xl border ${
                  errors.admin_password ? "border-red-300" : "border-gray-300"
                } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors pr-12`}
                placeholder="••••••••"
              />
              <button
                type="button"
                onClick={() => setShowPassword((prev) => !prev)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
              >
                {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
              </button>
            </div>
            {errors.admin_password && (
              <p className="mt-1 text-sm text-red-600">
                {errors.admin_password}
              </p>
            )}
            {formData.admin_password &&
              !errors.admin_password &&
              passwordStrength && (
                <p className={`mt-1 text-sm ${getPasswordStrengthColor()}`}>
                  Password strength: {passwordStrength}
                </p>
              )}
            <p className="mt-1 text-xs text-gray-500">
              Must contain: 8+ chars, uppercase, lowercase, number, special
              character
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Confirm Password *
            </label>
            <div className="relative">
              <input
                type={showConfirmPassword ? "text" : "password"}
                value={formData.admin_confirm_password}
                onChange={(e) =>
                  updateFormData("admin_confirm_password", e.target.value)
                }
                className={`w-full px-4 py-3 rounded-xl border ${
                  errors.admin_confirm_password
                    ? "border-red-300"
                    : "border-gray-300"
                } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors pr-12`}
                placeholder="••••••••"
              />
              <button
                type="button"
                onClick={() => setShowConfirmPassword((prev) => !prev)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
              >
                {showConfirmPassword ? <EyeOff size={20} /> : <Eye size={20} />}
              </button>
            </div>
            {errors.admin_confirm_password && (
              <p className="mt-1 text-sm text-red-600">
                {errors.admin_confirm_password}
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// ===================== STEP 3 =====================
function HotelContactStep({
  formData,
  updateFormData,
  errors,
  setFieldError,
  clearFieldError,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  setFieldError: (field: string, error: string) => void;
  clearFieldError: (field: string) => void;
}) {
  const countries = [
    { code: "NP", name: "Nepal" },
    { code: "IN", name: "India" },
    { code: "US", name: "United States" },
    { code: "UK", name: "United Kingdom" },
    { code: "AU", name: "Australia" },
    { code: "CA", name: "Canada" },
    { code: "AE", name: "United Arab Emirates" },
  ];

  useEffect(() => {
    if (!formData.hotel_phone.trim()) setFieldError("hotel_phone", "Hotel phone number is required");
    else clearFieldError("hotel_phone");
  }, [formData.hotel_phone, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.hotel_address.trim()) setFieldError("hotel_address", "Address is required");
    else clearFieldError("hotel_address");
  }, [formData.hotel_address, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.city.trim()) setFieldError("city", "City is required");
    else clearFieldError("city");
  }, [formData.city, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.country) setFieldError("country", "Country is required");
    else clearFieldError("country");
  }, [formData.country, setFieldError, clearFieldError]);

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">
          Contact Information
        </h3>
        <p className="text-gray-600">Where is your hotel located?</p>
      </div>

      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Hotel Phone Number *
          </label>
          <input
            type="tel"
            value={formData.hotel_phone}
            onChange={(e) => updateFormData("hotel_phone", e.target.value)}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.hotel_phone ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="1234567890"
          />
          {errors.hotel_phone && (
            <p className="mt-1 text-sm text-red-600">{errors.hotel_phone}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Address *
          </label>
          <textarea
            value={formData.hotel_address}
            onChange={(e) => updateFormData("hotel_address", e.target.value)}
            rows={3}
            className={`w-full px-4 py-3 rounded-xl border ${
              errors.hotel_address ? "border-red-300" : "border-gray-300"
            } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            placeholder="123 Main Street, Suite 100"
          />
          {errors.hotel_address && (
            <p className="mt-1 text-sm text-red-600">{errors.hotel_address}</p>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              City *
            </label>
            <input
              type="text"
              value={formData.city}
              onChange={(e) => updateFormData("city", e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border ${
                errors.city ? "border-red-300" : "border-gray-300"
              } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
              placeholder="New York"
            />
            {errors.city && (
              <p className="mt-1 text-sm text-red-600">{errors.city}</p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Country *
            </label>
            <select
              value={formData.country}
              onChange={(e) => updateFormData("country", e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border ${
                errors.country ? "border-red-300" : "border-gray-300"
              } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            >
              <option value="">Select a country</option>
              {countries.map((country) => (
                <option key={country.code} value={country.code}>
                  {country.name}
                </option>
              ))}
            </select>
            {errors.country && (
              <p className="mt-1 text-sm text-red-600">{errors.country}</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// ===================== STEP 4 =====================
function BusinessSettingsStep({
  formData,
  updateFormData,
  errors,
  setFieldError,
  clearFieldError,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  setFieldError: (field: string, error: string) => void;
  clearFieldError: (field: string) => void;
}) {
  const timezones = [
    "America/New_York",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "Europe/London",
    "Europe/Paris",
    "Asia/Kathmandu",
    "Asia/Tokyo",
    "Asia/Dubai",
    "UTC",
  ];

  const currencies = [
    { code: "NPR", symbol: "₹", name: "Nepalese Rupee" },
    { code: "USD", symbol: "$", name: "US Dollar" },
    { code: "EUR", symbol: "€", name: "Euro" },
    { code: "GBP", symbol: "£", name: "British Pound" },
    { code: "INR", symbol: "₹", name: "Indian Rupee" },
    { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  ];

  useEffect(() => {
    if (!formData.timezone) setFieldError("timezone", "Timezone is required");
    else clearFieldError("timezone");
  }, [formData.timezone, setFieldError, clearFieldError]);

  useEffect(() => {
    if (!formData.currency) setFieldError("currency", "Currency is required");
    else clearFieldError("currency");
  }, [formData.currency, setFieldError, clearFieldError]);

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">
          Business Settings
        </h3>
        <p className="text-gray-600">Configure your business preferences</p>
      </div>

      <div className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Timezone *
            </label>
            <select
              value={formData.timezone}
              onChange={(e) => updateFormData("timezone", e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border ${
                errors.timezone ? "border-red-300" : "border-gray-300"
              } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            >
              <option value="">Select timezone</option>
              {timezones.map((tz) => (
                <option key={tz} value={tz}>
                  {tz}
                </option>
              ))}
            </select>
            {errors.timezone && (
              <p className="mt-1 text-sm text-red-600">{errors.timezone}</p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Currency *
            </label>
            <select
              value={formData.currency}
              onChange={(e) => updateFormData("currency", e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border ${
                errors.currency ? "border-red-300" : "border-gray-300"
              } focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors`}
            >
              <option value="">Select currency</option>
              {currencies.map((curr) => (
                <option key={curr.code} value={curr.code}>
                  {curr.code} - {curr.name} ({curr.symbol})
                </option>
              ))}
            </select>
            {errors.currency && (
              <p className="mt-1 text-sm text-red-600">{errors.currency}</p>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Tax Rate (%) *
            </label>
            <div className="relative">
              <input
                type="number"
                min="0"
                max="50"
                step="0.01"
                value={formData.tax_rate}
                onChange={(e) =>
                  updateFormData("tax_rate", parseFloat(e.target.value) || 0)
                }
                className="w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors pl-12"
                placeholder="10.00"
              />
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">
                <PercentIcon size={20} />
              </div>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Service Charge (%) *
            </label>
            <div className="relative">
              <input
                type="number"
                min="0"
                max="20"
                step="0.01"
                value={formData.service_charge}
                onChange={(e) =>
                  updateFormData(
                    "service_charge",
                    parseFloat(e.target.value) || 0,
                  )
                }
                className="w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-amber-500 focus:border-transparent transition-colors pl-12"
                placeholder="5.00"
              />
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">
                <PercentIcon size={20} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
type EsewaFormFields = {
  amount: number;
  tax_amount: number;
  total_amount: number;
  transaction_uuid: string;
  product_code: string;
  product_service_charge: number;
  product_delivery_charge: number;
  success_url: string;
  failure_url: string;
  signed_field_names: string;
  signature: string;
};
// ===================== STEP 5 =====================
function SubscriptionStep({
  formData,
  updateFormData,
  errors,
  plans,
  loading,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  plans: SubscriptionPlan[];
  loading: boolean;
}) {
  const [selectedPlan, setSelectedPlan] = useState<string | null>(
    formData.subscription_plan_id || null,
  );

  useEffect(() => {
    if (selectedPlan) {
      updateFormData("subscription_plan_id", selectedPlan);
    }
  }, [selectedPlan, updateFormData]);

  if (loading) {
    return (
      <div className="space-y-6">
        <div>
          <h3 className="text-2xl font-bold text-gray-900 mb-2">
            Choose Your Plan
          </h3>
          <p className="text-gray-600">
            Select the perfect plan for your business
          </p>
        </div>
        <div className="flex justify-center items-center py-12">
          <Loader2 className="h-8 w-8 text-amber-500 animate-spin" />
        </div>
      </div>
    );
  }

  const sortedPlans = [...plans].sort(
    (a, b) => a.display_order - b.display_order,
  );

  const paymentMethods: {
    value: PaymentMethod;
    label: string;
    icon: React.ReactNode;
    desc: string;
  }[] = [
    {
      value: "esewa",
      label: "eSewa",
      icon: <Wallet className="h-5 w-5" />,
      desc: "Pay with eSewa wallet",
    },
    {
      value: "khalti",
      label: "Khalti",
      icon: <Smartphone className="h-5 w-5" />,
      desc: "Pay with Khalti",
    },

  ];

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">
          Choose Your Plan
        </h3>
        <p className="text-gray-600">
          Select the perfect plan for your business
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Billing Cycle *
          </label>
          <div className="grid grid-cols-2 gap-3">
            <button
              type="button"
              onClick={() => updateFormData("billing_cycle", "monthly")}
              className={`py-3 rounded-xl border font-medium transition-colors ${
                formData.billing_cycle === "monthly"
                  ? "border-amber-500 bg-amber-50 text-amber-700"
                  : "border-gray-300 text-gray-700"
              }`}
            >
              Monthly
            </button>

            <button
              type="button"
              onClick={() => updateFormData("billing_cycle", "yearly")}
              className={`py-3 rounded-xl border font-medium transition-colors ${
                formData.billing_cycle === "yearly"
                  ? "border-amber-500 bg-amber-50 text-amber-700"
                  : "border-gray-300 text-gray-700"
              }`}
            >
              Yearly
            </button>
          </div>
          {errors.billing_cycle && (
            <p className="text-sm text-red-600 mt-1">{errors.billing_cycle}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Payment Method *
          </label>
          <div className="grid grid-cols-1 gap-3">
            {paymentMethods.map((method) => (
              <button
                key={method.value}
                type="button"
                onClick={() => updateFormData("payment_method", method.value)}
                className={`py-3 px-4 rounded-xl border text-left font-medium transition-colors ${
                  formData.payment_method === method.value
                    ? "border-amber-500 bg-amber-50 text-amber-700"
                    : "border-gray-300 text-gray-700"
                }`}
              >
                <div className="flex items-center gap-3">
                  {method.icon}
                  <div>
                    <div className="font-semibold">{method.label}</div>
                    <div className="text-xs text-gray-500">{method.desc}</div>
                  </div>
                </div>
              </button>
            ))}
          </div>
          {errors.payment_method && (
            <p className="text-sm text-red-600 mt-1">{errors.payment_method}</p>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {sortedPlans.map((plan) => {
          const planPrice = hotelRegistrationService.getPlanPrice(
            plan,
            formData.billing_cycle as BillingCycle,
          );

          return (
            <div
              key={plan.id}
              onClick={() => setSelectedPlan(plan.id)}
              className={`relative rounded-2xl border-2 p-6 cursor-pointer transition-all duration-300 ${
                selectedPlan === plan.id
                  ? "border-amber-500 bg-gradient-to-b from-amber-50 to-orange-50"
                  : "border-gray-200 hover:border-amber-300"
              }`}
            >
              <div className="flex items-center justify-between mb-4">
                <h4 className="text-xl font-bold text-gray-900">
                  {plan.plan_name}
                </h4>
                {selectedPlan === plan.id && (
                  <div className="p-1 bg-amber-500 rounded-full">
                    <Check className="h-4 w-4 text-white" />
                  </div>
                )}
              </div>

              <div className="mb-4">
                <div className="flex items-baseline">
                  <span className="text-3xl font-bold text-gray-900">
                    रु{hotelRegistrationService.formatPrice(planPrice)}
                  </span>
                  <span className="ml-2 text-gray-500">
                    {hotelRegistrationService.getBillingLabel(
                      formData.billing_cycle as BillingCycle,
                    )}
                  </span>
                </div>
                <p className="text-sm text-gray-600">{plan.description}</p>
              </div>

              <div className="space-y-2 mb-6">
                <div className="flex items-center gap-2">
                  <Users className="h-4 w-4 text-gray-400" />
                  <span className="text-sm text-gray-600">
                    Up to {plan.max_staff} staff
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Table className="h-4 w-4 text-gray-400" />
                  <span className="text-sm text-gray-600">
                    {plan.max_tables} tables
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Utensils className="h-4 w-4 text-gray-400" />
                  <span className="text-sm text-gray-600">
                    {plan.max_menu_items} menu items
                  </span>
                </div>
              </div>

              <div className="space-y-2 mb-6">
                {plan.features &&
                  Object.entries(plan.features).map(
                    ([key, value]) =>
                      value && (
                        <div key={key} className="flex items-center gap-2">
                          <CheckCircle className="h-4 w-4 text-green-500" />
                          <span className="text-sm text-gray-600 capitalize">
                            {key.replace(/_/g, " ")}
                          </span>
                        </div>
                      ),
                  )}
              </div>

              <button
                type="button"
                className={`w-full py-3 rounded-lg font-semibold transition-colors ${
                  selectedPlan === plan.id
                    ? "bg-gradient-to-r from-amber-500 to-orange-500 text-white"
                    : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                }`}
              >
                {selectedPlan === plan.id ? "Selected" : "Select Plan"}
              </button>
            </div>
          );
        })}
      </div>

      {errors.subscription_plan_id && (
        <p className="text-sm text-red-600">{errors.subscription_plan_id}</p>
      )}
    </div>
  );
}

// ===================== STEP 6 =====================
function TermsStep({
  formData,
  updateFormData,
  errors,
  platformTerms,
  privacyPolicy,
  cancellationPolicy,
  loading,
  onViewFullTerms,
}: {
  formData: any;
  updateFormData: (field: any, value: any) => void;
  errors: Record<string, string>;
  platformTerms: any;
  privacyPolicy: any;
  cancellationPolicy: any;
  loading: boolean;
  onViewFullTerms: (type: string) => void;
}) {
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const allTermIds = [
    platformTerms?.id,
    privacyPolicy?.id,
    cancellationPolicy?.id,
  ].filter(Boolean);

  const handleTermsChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const checked = e.target.checked;
    updateFormData("accept_terms", checked);

    if (checked) {
      const newIds = [...(formData.accepted_terms_ids || [])];
      allTermIds.forEach((termId) => {
        if (termId && !newIds.includes(termId)) {
          newIds.push(termId);
        }
      });
      updateFormData("accepted_terms_ids", newIds);
    } else {
      updateFormData("accepted_terms_ids", []);
    }
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div>
          <h3 className="text-2xl font-bold text-gray-900 mb-2">
            Terms & Conditions
          </h3>
          <p className="text-gray-600">Loading terms...</p>
        </div>
        <div className="flex justify-center items-center py-12">
          <Loader2 className="h-8 w-8 text-amber-500 animate-spin" />
        </div>
      </div>
    );
  }

  const termsSections = [
    {
      id: "platform",
      title: "Terms of Service",
      content:
        platformTerms?.content || "Terms of service will be displayed here.",
      version: platformTerms?.version,
      effective: platformTerms?.effective_from,
      icon: <FileText className="h-5 w-5" />,
    },
    {
      id: "privacy",
      title: "Privacy Policy",
      content:
        privacyPolicy?.content || "Privacy policy will be displayed here.",
      version: privacyPolicy?.version,
      effective: privacyPolicy?.effective_from,
      icon: <Shield className="h-5 w-5" />,
    },
    {
      id: "cancellation",
      title: "Cancellation & Refund Policy",
      content:
        cancellationPolicy?.content ||
        "Cancellation policy will be displayed here.",
      version: cancellationPolicy?.version,
      effective: cancellationPolicy?.effective_from,
      icon: <AlertCircle className="h-5 w-5" />,
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">
          Terms & Conditions
        </h3>
        <p className="text-gray-600">Please review and accept our terms</p>
      </div>

      <div className="space-y-6">
        {termsSections.map((section) => (
          <div
            key={section.id}
            className="border border-gray-200 rounded-xl overflow-hidden"
          >
            <div className="w-full flex items-center justify-between p-4 bg-gray-50">
              <button
                type="button"
                onClick={() =>
                  setExpandedSection(
                    expandedSection === section.id ? null : section.id,
                  )
                }
                className="flex items-center gap-3 flex-1 text-left"
              >
                <div className="p-2 bg-amber-100 rounded-lg">
                  {section.icon}
                </div>
                <div className="text-left">
                  <h4 className="font-semibold text-gray-900">
                    {section.title}
                  </h4>
                  {section.version && (
                    <p className="text-xs text-gray-500">
                      Version {section.version}
                    </p>
                  )}
                </div>
              </button>

              <div className="flex items-center gap-3">
                <span
                  onClick={() => onViewFullTerms(section.id)}
                  className="text-sm text-amber-600 hover:text-amber-700 font-medium cursor-pointer"
                >
                  View Full
                </span>
                {expandedSection === section.id ? (
                  <ChevronUp className="h-5 w-5 text-gray-400" />
                ) : (
                  <ChevronDown className="h-5 w-5 text-gray-400" />
                )}
              </div>
            </div>

            {expandedSection === section.id && (
              <div className="p-4 bg-white border-t border-gray-200">
                <div className="prose prose-sm max-w-none text-gray-600 max-h-60 overflow-y-auto">
                  {String(section.content ?? "")
                    .split("\n")
                    .filter((paragraph: string) => paragraph.trim() !== "")
                    .map((paragraph: string, idx: number) => (
                      <p key={`${section.id}-${idx}`} className="mb-3">
                        {paragraph}
                      </p>
                    ))}
                </div>
                {section.effective && (
                  <p className="text-xs text-gray-400 mt-3">
                    Effective from:{" "}
                    {new Date(section.effective).toLocaleDateString()}
                  </p>
                )}
              </div>
            )}
          </div>
        ))}

        <div className="space-y-4 mt-6">
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.accept_terms}
              onChange={handleTermsChange}
              className="mt-1 w-5 h-5 rounded border-gray-300 text-amber-600 focus:ring-amber-500"
            />
            <div>
              <span className="font-medium text-gray-900">
                I agree to the Terms of Service, Privacy Policy, and
                Cancellation Policy *
              </span>
              <p className="text-sm text-gray-600 mt-1">
                You must accept all policies to use CloudCafe
              </p>
            </div>
          </label>

          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.accept_marketing}
              onChange={(e) =>
                updateFormData("accept_marketing", e.target.checked)
              }
              className="mt-1 w-5 h-5 rounded border-gray-300 text-amber-600 focus:ring-amber-500"
            />
            <div>
              <span className="font-medium text-gray-900">
                Send me updates and tips
              </span>
              <p className="text-sm text-gray-600 mt-1">
                Receive emails about new features, best practices, and special
                offers
              </p>
            </div>
          </label>
        </div>

        {errors.accept_terms && (
          <p className="text-sm text-red-600">{errors.accept_terms}</p>
        )}
      </div>
    </div>
  );
}

// ===================== STEP 7 =====================
function ReviewStep({
  formData,
  plans,
  platformTerms,
  privacyPolicy,
  cancellationPolicy,
  onEdit,
  onSubmit,
  isSubmitting,
  registrationType,
}: {
  formData: any;
  plans: SubscriptionPlan[];
  platformTerms: any;
  privacyPolicy: any;
  cancellationPolicy: any;
  onEdit: (step: number) => void;
  onSubmit: () => void;
  isSubmitting: boolean;
  registrationType: RegistrationType;
}) {
  const selectedPlan = plans.find(
    (p) => p.id === formData.subscription_plan_id,
  );

  const allTermIds = [
    platformTerms?.id,
    privacyPolicy?.id,
    cancellationPolicy?.id,
  ].filter(Boolean);

  const acceptedIds = formData.accepted_terms_ids || [];
  const termsAccepted =
    formData.accept_terms === true && acceptedIds.length === allTermIds.length;

  const computedPrice = hotelRegistrationService.getPlanPrice(
    selectedPlan,
    formData.billing_cycle as BillingCycle,
  );

  const sections = [
    {
      title: "Hotel Details",
      icon: <Building2 className="h-5 w-5" />,
      step: 1,
      fields: [
        { label: "Hotel Name", value: formData.hotel_name },
        { label: "URL Slug", value: formData.hotel_slug },
      ],
    },
    {
      title: "Admin Account",
      icon: <User className="h-5 w-5" />,
      step: 2,
      fields: [
        { label: "Admin Name", value: formData.admin_name },
        { label: "Email", value: formData.admin_email },
        { label: "Phone", value: formData.admin_phone },
      ],
    },
    {
      title: "Contact Information",
      icon: <MapPin className="h-5 w-5" />,
      step: 3,
      fields: [
        { label: "Hotel Phone", value: formData.hotel_phone },
        { label: "Address", value: formData.hotel_address },
        { label: "City", value: formData.city },
        { label: "Country", value: formData.country },
      ],
    },
    {
      title: "Business Settings",
      icon: <Briefcase className="h-5 w-5" />,
      step: 4,
      fields: [
        { label: "Timezone", value: formData.timezone },
        { label: "Currency", value: formData.currency },
        { label: "Tax Rate", value: `${formData.tax_rate}%` },
        { label: "Service Charge", value: `${formData.service_charge}%` },
      ],
    },
    {
      title: "Subscription",
      icon: <CardIcon className="h-5 w-5" />,
      step: 5,
      fields: [
        {
          label: "Selected Plan",
          value: selectedPlan ? selectedPlan.plan_name : "Not selected",
        },
        {
          label: "Billing Cycle",
          value: formData.billing_cycle,
        },
        {
          label: "Payment Method",
          value: hotelRegistrationService.getPaymentMethodLabel(
            formData.payment_method as PaymentMethod,
          ),
        },
        {
          label: "Price",
          value: selectedPlan
            ? `रु${hotelRegistrationService.formatPrice(computedPrice)}${hotelRegistrationService.getBillingLabel(
                formData.billing_cycle as BillingCycle,
              )}`
            : "-",
        },
      ],
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-3 mb-2">
          {registrationType === "trial" ? (
            <div className="p-2 bg-gradient-to-r from-amber-500 to-orange-500 rounded-lg">
              <Gift className="h-6 w-6 text-white" />
            </div>
          ) : (
            <div className="p-2 bg-gradient-to-r from-emerald-500 to-teal-600 rounded-lg">
              <Zap className="h-6 w-6 text-white" />
            </div>
          )}
          <h3 className="text-2xl font-bold text-gray-900">
            {registrationType === "trial"
              ? "Start Your Free Trial"
              : "Complete Your Subscription"}
          </h3>
        </div>
      </div>

      <div className="space-y-6">
        {sections.map((section, index) => (
          <div
            key={index}
            className="bg-white rounded-xl border border-gray-200 p-6"
          >
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-gradient-to-br from-amber-100 to-orange-100 rounded-lg">
                  {section.icon}
                </div>
                <h4 className="font-bold text-gray-900">{section.title}</h4>
              </div>
              <button
                type="button"
                onClick={() => onEdit(section.step)}
                className="flex items-center gap-2 text-amber-600 hover:text-amber-700 font-medium"
              >
                <Edit className="h-4 w-4" />
                Edit
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {section.fields.map((field, fieldIndex) => (
                <div key={fieldIndex}>
                  <p className="text-sm text-gray-500 mb-1">{field.label}</p>
                  <p className="font-medium text-gray-900">
                    {field.value || "-"}
                  </p>
                </div>
              ))}
            </div>
          </div>
        ))}

        {selectedPlan && (
          <div
            className={`rounded-xl border p-6 ${
              registrationType === "trial"
                ? "bg-gradient-to-br from-amber-50 to-orange-50 border-amber-200"
                : "bg-gradient-to-br from-emerald-50 to-teal-50 border-emerald-200"
            }`}
          >
            <div className="flex items-center gap-3 mb-4">
              <div
                className={`p-3 rounded-xl ${
                  registrationType === "trial"
                    ? "bg-gradient-to-br from-amber-500 to-orange-500"
                    : "bg-gradient-to-br from-emerald-500 to-teal-600"
                }`}
              >
                {registrationType === "trial" ? (
                  <Gift className="h-6 w-6 text-white" />
                ) : (
                  <Zap className="h-6 w-6 text-white" />
                )}
              </div>
              <div>
                <h4 className="font-bold text-gray-900">
                  {registrationType === "trial"
                    ? "Free Trial Summary"
                    : "Payment Summary"}
                </h4>
              </div>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center py-2 border-b border-gray-200">
                <span className="text-gray-700">Plan:</span>
                <span className="font-semibold text-gray-900">
                  {selectedPlan.plan_name}
                </span>
              </div>

              {registrationType === "subscription" && (
                <>
                  <div className="flex justify-between items-center py-2 border-b border-gray-200">
                    <span className="text-gray-700">Billing cycle:</span>
                    <span className="font-semibold text-gray-900 capitalize">
                      {formData.billing_cycle}
                    </span>
                  </div>

                  <div className="flex justify-between items-center py-2 border-b border-gray-200">
                    <span className="text-gray-700">Payment method:</span>
                    <span className="font-semibold text-gray-900">
                      {hotelRegistrationService.getPaymentMethodLabel(
                        formData.payment_method as PaymentMethod,
                      )}
                    </span>
                  </div>

                  <div className="flex justify-between items-center py-2">
                    <span className="text-gray-700">Total amount:</span>
                    <span className="text-2xl font-bold text-gray-900">
                      रु{hotelRegistrationService.formatPrice(computedPrice)}
                    </span>
                  </div>
                </>
              )}

              <div className="mt-4 p-4 rounded-lg bg-white/50">
                <p className="text-sm text-gray-600 flex items-start gap-2">
                  {registrationType === "trial" ? (
                    <>
                      <Clock className="h-4 w-4 text-amber-500 flex-shrink-0 mt-0.5" />
                      <span>
                        Your 14-day free trial starts immediately.
                      </span>
                    </>
                  ) : (
                    <>
                      <AlertCircle className="h-4 w-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                      <span>
                        You will be redirected to{" "}
                        {hotelRegistrationService.getPaymentMethodLabel(
                          formData.payment_method as PaymentMethod,
                        )}{" "}
                        to complete payment.
                      </span>
                    </>
                  )}
                </p>
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="flex flex-col sm:flex-row gap-4 pt-6">
        <button
          onClick={onSubmit}
          disabled={isSubmitting || !termsAccepted || !selectedPlan}
          className={`flex-1 py-4 rounded-xl font-semibold transition-all duration-300 shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3 ${
            registrationType === "trial"
              ? "bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white"
              : "bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white"
          }`}
        >
          {isSubmitting ? (
            <>
              <Loader2 className="h-5 w-5 animate-spin" />
              {registrationType === "trial"
                ? "Starting Trial..."
                : "Redirecting to Payment..."}
            </>
          ) : registrationType === "trial" ? (
            <>
              <Gift className="h-5 w-5" />
              Start 14-Day Free Trial
            </>
          ) : (
            <>
              <Zap className="h-5 w-5" />
              Pay रु {hotelRegistrationService.formatPrice(computedPrice)} via{" "}
              {hotelRegistrationService.getPaymentMethodLabel(
                formData.payment_method as PaymentMethod,
              )}
            </>
          )}
        </button>
      </div>
    </div>
  );
}

// ===================== MAIN =====================
function HotelRegistrationContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const planId = searchParams?.get("plan") || "";
  const registrationType =
    (searchParams?.get("type") as RegistrationType) || "subscription";

  const dispatch = useDispatch<AppDispatch>();
  const { plans, loading: plansLoading } = useSelector(
    (state: RootState) => state.subscription,
  );
  const {
    platformTerms,
    privacyPolicy,
    cancellationPolicy,
    loading: termsLoading,
  } = useTerms();

  useEffect(() => {
    dispatch(fetchSubscriptionPlans());
  }, [dispatch]);

  const {
    formData,
    formErrors,
    currentStep,
    submitting,
    selectedPlan,
    setCurrentStep,
    setFieldError,
    clearFieldError,
    updateFormData,
    handleNextStep,
    handlePrevStep,
    handleSubmitRegistration,
  } = useHotelRegistration({
    registrationType,
    initialPlanId: planId,
    plans: plans as SubscriptionPlan[],
    platformTerms,
    privacyPolicy,
    cancellationPolicy,
  });

  useEffect(() => {
    if (planId && planId !== formData.subscription_plan_id) {
      updateFormData("subscription_plan_id", planId);
    }
  }, [planId, formData.subscription_plan_id, updateFormData]);

  const totalSteps = 7;
  const progressPercentage = Math.round((currentStep / totalSteps) * 100);

  const handleEditStep = useCallback((step: number) => {
    setCurrentStep(step);
  }, [setCurrentStep]);

  const handleViewFullTerms = useCallback((type: string) => {
    window.open(`/terms/${type}`, "_blank");
  }, []);
const submitEsewaForm = (
  paymentUrl: string,
  fields: EsewaFormFields,
): void => {
  const form = document.createElement("form");
  form.method = "POST";
  form.action = paymentUrl;
  form.style.display = "none";

  Object.entries(fields).forEach(([key, value]) => {
    const input = document.createElement("input");
    input.type = "hidden";
    input.name = key;
    input.value = String(value);
    form.appendChild(input);
  });

  document.body.appendChild(form);
  form.submit();
};
const handleSubmit = useCallback(async () => {
  try {
    toast.loading(
      registrationType === "trial"
        ? "Starting your free trial..."
        : "Redirecting to payment...",
      { id: "registration" }
    );

    const apiResponse = await handleSubmitRegistration();

    // axios response body
    const body = apiResponse?.data ?? apiResponse;

    // support both:
    // 1) { status, message, data: {...} }
    // 2) { status, message, payment_method, payment_url, form_fields }
    const payload = body?.data ?? body;

    const provider = payload?.payment_method;
    const paymentUrl = payload?.payment_url;
    const formFields = payload?.form_fields;

    if (provider === "esewa" && paymentUrl && formFields) {
      toast.success("Redirecting to eSewa...", { id: "registration" });
      submitEsewaForm(paymentUrl, formFields);
      return;
    }

    if (provider === "khalti" && paymentUrl) {
      toast.success("Redirecting to Khalti...", { id: "registration" });
      window.location.assign(paymentUrl);
      return;
    }

    toast.success(body?.message || "Registration started successfully", {
      id: "registration",
    });
  } catch (err: any) {
    toast.error(getActualErrorMessage(err), {
      id: "registration",
    });
  }
}, [handleSubmitRegistration, registrationType]);

  const renderStep = () => {
    switch (currentStep) {
      case 1:
        return (
          <HotelDetailsStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            setFieldError={setFieldError}
            clearFieldError={clearFieldError}
          />
        );
      case 2:
        return (
          <AdminDetailsStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            setFieldError={setFieldError}
            clearFieldError={clearFieldError}
          />
        );
      case 3:
        return (
          <HotelContactStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            setFieldError={setFieldError}
            clearFieldError={clearFieldError}
          />
        );
      case 4:
        return (
          <BusinessSettingsStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            setFieldError={setFieldError}
            clearFieldError={clearFieldError}
          />
        );
      case 5:
        return (
          <SubscriptionStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            plans={plans as SubscriptionPlan[]}
            loading={plansLoading}
          />
        );
      case 6:
        return (
          <TermsStep
            formData={formData}
            updateFormData={updateFormData}
            errors={formErrors}
            platformTerms={platformTerms}
            privacyPolicy={privacyPolicy}
            cancellationPolicy={cancellationPolicy}
            loading={termsLoading}
            onViewFullTerms={handleViewFullTerms}
          />
        );
      case 7:
        return (
          <ReviewStep
            formData={formData}
            plans={plans as SubscriptionPlan[]}
            platformTerms={platformTerms}
            privacyPolicy={privacyPolicy}
            cancellationPolicy={cancellationPolicy}
            onEdit={handleEditStep}
            onSubmit={handleSubmit}
            isSubmitting={submitting}
            registrationType={registrationType}
          />
        );
      default:
        return null;
    }
  };

  const steps = [
    { number: 1, title: "Hotel Details", icon: <Building2 className="h-5 w-5" /> },
    { number: 2, title: "Admin Account", icon: <User className="h-5 w-5" /> },
    { number: 3, title: "Contact Info", icon: <MapPin className="h-5 w-5" /> },
    { number: 4, title: "Business Settings", icon: <Briefcase className="h-5 w-5" /> },
    { number: 5, title: "Subscription", icon: <CardIcon className="h-5 w-5" /> },
    { number: 6, title: "Terms", icon: <FileText className="h-5 w-5" /> },
    { number: 7, title: "Review", icon: <FileCheck className="h-5 w-5" /> },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-orange-50">
      <Toaster
        position="top-right"
        toastOptions={{
          duration: 4000,
          style: {
            background: "#1f2937",
            color: "#fff",
            borderRadius: "12px",
            border: "1px solid #374151",
          },
        }}
      />

      <header className="bg-white/80 backdrop-blur-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div
              className="flex items-center gap-3 cursor-pointer"
              onClick={() => router.push("/")}
            >
              <div className="p-2 bg-gradient-to-br from-amber-500 to-orange-500 rounded-xl">
                <Hotel className="h-7 w-7 text-white" />
              </div>
              <div>
                <span className="text-2xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">
                  CloudCafe
                </span>
                <div className="h-1 w-12 bg-gradient-to-r from-amber-500 to-orange-500 rounded-full mt-1"></div>
              </div>
            </div>

            <div className="flex items-center gap-4">
              {registrationType === "trial" ? (
                <div className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-amber-100 to-orange-100 rounded-xl">
                  <Gift className="h-4 w-4 text-amber-600" />
                  <span className="text-sm font-semibold text-amber-700">
                    Free Trial
                  </span>
                </div>
              ) : (
                <div className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-emerald-100 to-teal-100 rounded-xl">
                  <Zap className="h-4 w-4 text-emerald-600" />
                  <span className="text-sm font-semibold text-emerald-700">
                    Subscription
                  </span>
                </div>
              )}
              <button
                onClick={() => router.push("/")}
                className="text-gray-600 hover:text-amber-600 font-medium px-4 py-2 hover:bg-amber-50 rounded-lg transition-colors"
              >
                Back to Home
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
          <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-b border-amber-200 p-6">
            <div className="mb-6">
              <h1 className="text-3xl font-bold text-gray-900 mb-2">
                {registrationType === "trial"
                  ? "Start Your Free Trial"
                  : "Register Your Cafe/Resturant"}
              </h1>
              <p className="text-gray-600">
                {registrationType === "trial"
                  ? "Complete the form to start your 14-day free trial."
                  : "Complete the form to purchase your subscription."}
              </p>
            </div>

            <div className="mb-2">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-gray-700">
                  Step {currentStep} of {totalSteps}
                </span>
                <span className="text-sm font-bold text-amber-600">
                  {progressPercentage}%
                </span>
              </div>
              <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-amber-500 to-orange-500 transition-all duration-300"
                  style={{ width: `${progressPercentage}%` }}
                />
              </div>
            </div>

            <div className="flex justify-between mt-6">
              {steps.map((step) => (
                <div
                  key={step.number}
                  className={`flex flex-col items-center relative ${
                    step.number < currentStep
                      ? "text-emerald-600"
                      : step.number === currentStep
                        ? "text-amber-600"
                        : "text-gray-400"
                  }`}
                >
                  <div
                    className={`w-10 h-10 rounded-full flex items-center justify-center mb-2 ${
                      step.number < currentStep
                        ? "bg-emerald-100 border-2 border-emerald-500"
                        : step.number === currentStep
                          ? "bg-amber-100 border-2 border-amber-500"
                          : "bg-gray-100 border-2 border-gray-300"
                    }`}
                  >
                    {step.number < currentStep ? (
                      <Check className="h-5 w-5" />
                    ) : (
                      step.icon
                    )}
                  </div>
                  <span className="text-xs font-medium text-center">
                    {step.title}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="p-6 md:p-8">
            {renderStep()}

            <div className="flex justify-between pt-8 mt-8 border-t border-gray-200">
              <button
                onClick={handlePrevStep}
                disabled={currentStep === 1 || submitting}
                className={`flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-colors ${
                  currentStep === 1 || submitting
                    ? "text-gray-400 cursor-not-allowed"
                    : "text-gray-700 hover:text-amber-600 hover:bg-amber-50"
                }`}
              >
                <ArrowLeft className="h-5 w-5" />
                Previous
              </button>

              {currentStep < totalSteps ? (
                <button
                  onClick={handleNextStep}
                  disabled={submitting}
                  className="bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-300 shadow-lg hover:shadow-xl flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Next Step
                  <ArrowRight className="h-5 w-5" />
                </button>
              ) : null}
            </div>
          </div>
        </div>
      </main>

      <footer className="mt-12 pb-8 text-center">
        <p className="text-gray-600 text-sm">
          By registering, you agree to our{" "}
          <button
            onClick={() => handleViewFullTerms("platform")}
            className="text-amber-600 hover:text-amber-700 font-medium"
          >
            Terms of Service
          </button>{" "}
          and{" "}
          <button
            onClick={() => handleViewFullTerms("privacy")}
            className="text-amber-600 hover:text-amber-700 font-medium"
          >
            Privacy Policy
          </button>
        </p>
      </footer>
    </div>
  );
}

export default function HotelRegistrationPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-orange-50 flex items-center justify-center">
          <div className="text-center">
            <Loader2 className="h-12 w-12 text-amber-500 animate-spin mx-auto mb-4" />
            <p className="text-gray-600">Loading registration form...</p>
          </div>
        </div>
      }
    >
      <HotelRegistrationContent />
    </Suspense>
  );
}